apiVersion: apps/v1
kind: Deployment
metadata:
        name: busybox-secret
        labels:
                app: busybox-secret
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: busybox-secret
        template:
                metadata:
                        labels:
                                app: busybox-secret
                spec:
                        containers:
                                - name: busybox
                                  image: busybox
                                  env:
                                          - name: USERNAME
                                            valueFrom:
                                                    secretKeyRef:
                                                            name: velotio-secret
                                                            key: username
                                          - name: PASSWORD
                                            valueFrom: 
                                                    secretKeyRef:
                                                            name: velotio-secret
                                                            key: password
