apiVersion: apps/v1
kind: Deployment
metadata:
        name: nginx
spec:
        replicas: 2
        template:
                metadata:
                        name: nginx
                        labels:
                                app: velotio
                spec:
                        containers:
                                - name: nginx-container
                                  image: nginx:1.7.8
                                  ports:
                                          - containerPort: 80
        selector:
                matchLabels:
                        app: velotio

