apiVersion: v1
kind: Pod
metadata:
        name: nginx
        labels:
                app: velotio
spec:
        containers:
                - name: nginx-container
                  image: nginx
                  ports:
                          - containerPort: 80
